---
data_dir: "../data/"
target_size: [224, 224]
batch_size: 1
# small and fast but inaccurate
model_name: "ViT-B-32"
pretrained: "laion2b_s34b_b79k"
# big and slow but more accurate
# model_name: "ViT-H-14-378-quickgelu"
# pretrained: "dfn5b"
learning_rate: 0.000005
epochs: 10
save_freq: 1
...
